version: '3'
services:
  nginx:
    image: nginx
    container_name: nginx1
    ports: 
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    depends_on:
      - node1
    restart: "unless-stopped"
  node1:
    image: momspt_server:0.5.9
    container_name: node1
    expose:
      - "3000"
    volumes:
      - ./momspt_server:/app
    restart: "unless-stopped"
