version: '3'
services:
  nginx:
    image: nginx:1.2.7
    container_name: nginx1
    ports: 
      - "80:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
    restart: "unless-stopped"
  node1:
    image: momspt_server:0.1.1
    container_name: node1
    expose:
      - "3000"
    volumes:
      - ./momspt_server:/app
    restart: "unless-stopped"
