openapi: 3.0.0
info:
  version: 0.0.1
  title: Momspt service server API(21.09.15)
  description: 맘스피티 어플리케이션의 API 리스트입니다.
  license:
    name: MIT
    url: https://spdx.org/licenses/MIT.html
  contact:
    name: HyunminLee
    email: gusals005@gmail.com
servers:
  - url: 'http://localhost:3000/'
paths:
  /user/signup:
    post:
      summary: 회원가입 API
      description: 처음 유저를 생성할 때 사용되는 회원가입 API입니다.
      tags:
        - user
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: 회원가입 요청 시 request 양식
          required: true
          schema:
            $ref: '#/Requests/Signup'
      responses:
        '201':
          $ref: '#/components/responses/SignupSuccess201'
        '400':
          $ref: '#/components/responses/SignupBad400'
  /user/login:
    post:
      summary: 로그인 API
      description: 로그인 시 작동하는 API입니다.
      tags:
        - user
      consumes:
        - "application/json"
      parameters:
        - in: body
          name: body
          description: Login 시 request 형식
          required: true
          schema:
            $ref: '#/Requests/Login'
      responses:
        '200':
          $ref: '#/components/responses/LoginSuccess200'
        '400':
          $ref: '#/components/responses/SignupBad400'
components:
  parameters: null
  schemas:
    User:
      type: object
      required:
        - _id
        - name
      properties:
        _id:
          type: number
          description: id
        name:
          type: string
          description: 유저 이름
  responses:
    Success200:
      description: 올바른 요청입니다.
      content:
        application/json:
          schema:
            $ref: '#/components/ResponseFormat/baseFormat'
          example:
            success: true
            message: 정상적으로 처리되었습니다.
    SignupSuccess201:
      description: 올바른 요청으로 요청하신 데이터를 생성합니다.
      content:
        application/json:
          schema:
            $ref: '#/components/ResponseFormat/signup201'
    SignupBad400:
      description: 해당 정보를 가진 유저가 존재합니다.
      content:
        application/json:
          schema:
            $ref: '#/components/ResponseFormat/baseFormat'
          example:
            success: false
            message: 해당 kakaoId를 가진 유저가 존재합니다.
    LoginSuccess200:
      description: 로그인을 성공하였습니다.
      content:
        application/json:
          schema:
            $ref: '#/components/ResponseFormat/login200'
    InternalServerError:
      description: 서버 에러
      content:
        application/json:
          schema:
            $ref: '#/components/ResponseFormat/baseFormat'
          example:
            success: false
            message: 서버 내부 오류
  ResponseFormat:
    baseFormat:
      type: object
      properties:
        success:
          type: boolean
        message:
          type: string
    signup201: 
      type: object
      properties:
        success:
          type: boolean
        user:
          $ref: '#/Requests/Signup'
    login200:
      type: object
      properties:
        success: 
          type: boolean
        token:
          type: string
          example: eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJuaWNrbmFtZSI6ImZpdCIsImlhdCI6MTYzMDY0NzE2NSwiZXhwIjoxNjMwNzMzNTY1LCJzdWIiOiJ1c2VySW5mbyJ9.5l5lK0N7kseEoZWhMcnDFUj8m9wQcrzuPI1Ep_BgMuE
        user:
          $ref: '#/Requests/Signup'
tags:
  - name: User
    description: 유저의 동작과 관련된 API들 모음

Requests:
  Signup:
    type: object
    properties:
      nickname:
        type: string
        example: fitsionary
      babyDue:
        type: string
        format: date
        example: "2021-09-15"
      weightBeforePregnancy:
        type: number
        format: "double"
        example: 54.6
      weightNow:
        type: number
        format: double
        example: 58.3
      heightNow:
        type: number
        format: double
        example: 164.3
      kakaoId:
        type: number
        format: integer
        example: 1896724603
  Login:
    type: object
    properties:
      kakaoId:
        type: number
        format: integer
        example: 1896724603
